### ISSUE TITLE
actor training script throws Error : ModuleNotFoundError: No module named 'llama'

### ISSUE THREAD

**Issue by sebastianschramm** [nebuly-ai/nebullvm#235]
While trying to run actor training of OPT-125M from huggingface the script throws an import error:
```
>> python artifacts/main.py artifacts/config/config.yaml --type ACTOR                            
Traceback (most recent call last):
  File "/nebullvm/apps/accelerate/chatllama/artifacts/main.py", line 3, in <module>
    from chatllama.rlhf.actor import ActorTrainer
  File "/nebullvm/apps/accelerate/chatllama/chatllama/rlhf/actor.py", line 16, in <module>
    from chatllama.llama_model import load_model
  File "/nebullvm/apps/accelerate/chatllama/chatllama/llama_model.py", line 26, in <module>
    from llama import Tokenizer
ModuleNotFoundError: No module named 'llama'
```

python 3.10
chatllama from main: 2227d3f40e8bb91cd8175a38b4debf763560cd7b

config.yaml:
```
actor_config:
  model: "facebook/opt-125m"
  model_path: "path-to-model"
  checkpoint_folder: "./models"
  tokenizer_folder: "path-to-tokenizer"
  train_dataset_path: "./artifacts/datasets/actor_dataset.json"
  validation_dataset_path: null
  # froze model embedding during training
  froze_embeddings: True
  # use fairscale layers to build the model instead of vanilla pytorch
  use_fairscale: False
  # max sequence length for the actor (i.e. prompt + completion) it depends on
  # the model used.
  max_sequence_length: 1024
  # max tokens generated by the actor (completion only)
  max_tokens: 512
  # temperature for the actor
  temperature: 0.9
  batch_size: 1
  # number iteration after print
  iteration_per_print: 1
  lr: 0.0001
  epochs: 32
  # deepspeed settings
  deepspeed_enable: False
  deepspeed_config_path: "path-to-deepspeed-conf"
```

I do not have the llama model nor do I want to use it.
Actor training does work for OPT-125M once I delay the import of `load_model`.

Possible fix: delay import of `from chatllama.llama_model import load_model` until model type check in rlhf/actor.py::ActorModel

I am happy to contribute with a MR once we agree on the expected behavior. I am not sure where the "llama" module is supposed to come from?

**Comment by diegofiori** [comment]
Hi @sebastianschramm, thank you for reaching out. I actually like the idea to move the import into the Actor `__init__` method. I would simply put it after 
```python
if config.model in llama_models:
```
since this is the unique part of the code where the load_model function is used. You are welcome to open a PR for avoiding the llama import while using HF models 😄
