### ISSUE TITLE
speedster usage

### ISSUE THREAD

**Issue by vinnitu** [nebuly-ai/nebullvm#272]
Hi!

Is it properly formed code usage optimized model?

```python
from transformers import AlbertTokenizer
from speedster load_model

tokenizer = AlbertTokenizer.from_pretrained("albert-base-v1")

text = "This is an example text for the huggingface model."
input_sample = tokenizer(text, return_tensors="pt")

optimized_model = load_model("model_save_path")

output = optimized_model(**input_sample)
print(output)
```

**Comment by valeriosofi** [comment]
Hello @vinnitu, I notice that you are missing the `import` keyword in line 2, it should be `from speedster import load_model
`. The other parts of the code should be ok, are you facing any error?

**Comment by vinnitu** [comment]
You are right, i fixed example

But question is still opened

**Comment by valeriosofi** [comment]
Well the code is correct assuming that you have previously optimized and saved the model in that path, do you have any specific question?

**Comment by vinnitu** [comment]
```
Traceback (most recent call last):
  File "test-speed-albert.py", line 12, in <module>
    result = tokenizer.batch_decode(output)
  File "/home/ai/.local/share/virtualenvs/test-speedster-fa_zu4ag/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3437, in batch_decode
    return [
  File "/home/ai/.local/share/virtualenvs/test-speedster-fa_zu4ag/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3438, in <listcomp>
    self.decode(
  File "/home/ai/.local/share/virtualenvs/test-speedster-fa_zu4ag/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3476, in decode
    return self._decode(
  File "/home/ai/.local/share/virtualenvs/test-speedster-fa_zu4ag/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 931, in _decode
    filtered_tokens = self.convert_ids_to_tokens(token_ids, skip_special_tokens=skip_special_tokens)
  File "/home/ai/.local/share/virtualenvs/test-speedster-fa_zu4ag/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 906, in convert_ids_to_tokens
    index = int(index)
ValueError: invalid literal for int() with base 10: 'l'
```

but main problem output is not indexes (but tensor) that is why decode doesn't work

Maybe you can give me woriking example to decode output to text?

**Comment by valeriosofi** [comment]
The problem is not related to speedster, the `batch_decode ` method of the tokenizer wants as input a list of tokenized input ids (which are int values), but you are trying to pass it the output of the AlbertModel (which outputs raw hidden-states). You should take a look at the hugging face docs: [batch_decode](https://huggingface.co/docs/transformers/main_classes/tokenizer#transformers.PreTrainedTokenizer.batch_decode) and [AlbertModel](https://huggingface.co/docs/transformers/model_doc/albert#transformers.AlbertModel). You can find examples of encoder-decoder models [here](https://huggingface.co/docs/transformers/model_doc/t5), and we have also a [notebook](https://github.com/nebuly-ai/nebullvm/blob/main/notebooks/speedster/huggingface/Accelerate_Hugging_Face_PyTorch_T5_with_Speedster.ipynb) about how to optimize them with speedster.
