### ISSUE TITLE
Tokenizer Issue

### ISSUE THREAD

**Issue by yradwan147** [nebuly-ai/nebullvm#297]
Whenever I try to train the model on the 7B LLaMa weights (Actor training), I get the following error:

Current device used :cuda
Start cleaning the dataset for Actor
Traceback (most recent call last):
  File "artifacts/main.py", line 59, in <module>
    BaseDataset.clean_dataset(config.actor)
  File "/opt/conda/envs/newCondaEnvironment/lib/python3.8/site-packages/chatllama/rlhf/dataset.py", line 136, in clean_dataset
    a_tokenizer = ActorModel.load_tokenizer(config)
  File "/opt/conda/envs/newCondaEnvironment/lib/python3.8/site-packages/chatllama/rlhf/actor.py", line 146, in load_tokenizer
    tokenizer = load_tokenizer()
TypeError: load_tokenizer() missing 1 required positional argument: 'tokenizer_path'

Even though my config.yaml file includes the tokenizer_path in the actor config:

actor_config:
  model: "llama-7B"
  model_folder: "/kaggle/input/chatllamadataset/7B"
  tokenizer_path: "/kaggle/input/chatllamadataset/tokenizer.model"

What is the issue here?

**Comment by allaccs** [comment]
Traceback (most recent call last):
  File "/workspace/llama/artifacts/main.py", line 59, in <module>
    BaseDataset.clean_dataset(config.actor)
  File "/usr/local/lib/python3.10/dist-packages/chatllama/rlhf/dataset.py", line 136, in clean_dataset
    a_tokenizer = ActorModel.load_tokenizer(config)
  File "/usr/local/lib/python3.10/dist-packages/chatllama/rlhf/actor.py", line 146, in load_tokenizer
    tokenizer = load_tokenizer()
TypeError: load_tokenizer() missing 1 required positional argument: 'tokenizer_path'

Same error here, I'm trying to train the 13B

**Comment by diegofiori** [comment]
Hi @yradwan147, thank you very much for pointing out the error. We recently changed the `load_tokenizer` function API and it looks like the LLaMA actor training file was not updated. We'll fix it very soon.

**Comment by diegofiori** [comment]
We fixed it in #300. Let me know if you encounter any other errors!
