### ISSUE TITLE
numpy API version 0xe vs 0xd

### ISSUE THREAD

**Issue by IamMarcIvanov** [nebuly-ai/nebullvm#8]
When trying to run the sample code provided in the readme I got an error 

> RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "test_pytorch.py", line 3, in <module>
    from nebullvm import optimize_torch_model
  File "<PATH_TO_ENV>/lib/python3.8/site-packages/nebullvm/__init__.py", line 1, in <module>
    from nebullvm.api.frontend.torch import optimize_torch_model  # noqa F401
  File "<PATH_TO_ENV>/lib/python3.8/site-packages/nebullvm/api/frontend/torch.py", line 8, in <module>
    from nebullvm.converters import ONNXConverter
  File "<PATH_TO_ENV>/lib/python3.8/site-packages/nebullvm/converters/__init__.py", line 1, in <module>
    from .converters import ONNXConverter  # noqa F401
  File "<PATH_TO_ENV>/lib/python3.8/site-packages/nebullvm/converters/converters.py", line 5, in <module>
    import tensorflow as tf
  File "<PATH_TO_ENV>/lib/python3.8/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "<PATH_TO_ENV>/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "<PATH_TO_ENV>/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 35, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "<PATH_TO_ENV>/lib/python3.8/site-packages/tensorflow/python/client/pywrap_tf_session.py", line 19, in <module>
    from tensorflow.python.client._pywrap_tf_session import *
ImportError: SystemError: <built-in method __contains__ of dict object at 0x7f7393496680> returned a result with an error set

when searching about 0xe and 0xd versions of numpy, [this](https://stackoverflow.com/questions/33859531/runtimeerror-module-compiled-against-api-version-a-but-this-version-of-numpy-is) page said to try and upgrade which I did after which the error changed and uninstalled the latest version of numpy and said that it could not find openvino:

> <PATH_TO_ENV>/lib/python3.8/site-packages/nebullvm/inference_learners/openvino.py:26: UserWarning: No valid OpenVino installation has been found. Trying to re-install it from source.
  warnings.warn(
Collecting openvino-dev
  Using cached openvino_dev-2021.4.2-3976-py3-none-any.whl (6.2 MB)
Collecting numpy<1.20,>=1.16.6
  Using cached numpy-1.19.5-cp38-cp38-manylinux2010_x86_64.whl (14.9 MB)
Collecting editdistance>=0.5.3
  Using cached editdistance-0.6.0-cp38-cp38-manylinux2010_x86_64.whl (286 kB)
Collecting pandas~=1.1.5
  Using cached pandas-1.1.5-cp38-cp38-manylinux1_x86_64.whl (9.3 MB)
Requirement already satisfied: pydicom>=2.1.2 in <PATH_TO_ENV>/lib/python3.8/site-packages (from openvino-dev) (2.2.2)
Collecting rawpy>=0.16.0
  Using cached rawpy-0.17.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)
Requirement already satisfied: jstyleson~=0.0.2 in <PATH_TO_ENV>/lib/python3.8/site-packages (from openvino-dev) (0.0.2)
Collecting defusedxml>=0.7.1
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: requests>=2.25.1 in <PATH_TO_ENV>/lib/python3.8/site-packages (from openvino-dev) (2.27.1)
Requirement already satisfied: PyYAML>=5.4.1 in <PATH_TO_ENV>/lib/python3.8/site-packages (from openvino-dev) (6.0)
Requirement already satisfied: py-cpuinfo>=7.0.0 in <PATH_TO_ENV>/lib/python3.8/site-packages (from openvino-dev) (8.0.0)
Collecting opencv-python==4.5.*
  Using cached opencv_python-4.5.5.62-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (60.4 MB)
Requirement already satisfied: tqdm>=4.54.1 in <PATH_TO_ENV>/lib/python3.8/site-packages (from openvino-dev) (4.62.3)
Collecting scipy~=1.5.4
  Using cached scipy-1.5.4-cp38-cp38-manylinux1_x86_64.whl (25.8 MB)
Collecting scikit-image>=0.17.2
  Using cached scikit_image-0.19.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.0 MB)
Requirement already satisfied: sentencepiece>=0.1.95 in <PATH_TO_ENV>/lib/python3.8/site-packages (from openvino-dev) (0.1.96)
Requirement already satisfied: shapely>=1.7.1 in <PATH_TO_ENV>/lib/python3.8/site-packages (from openvino-dev) (1.8.1.post1)
Collecting networkx~=2.5
  Using cached networkx-2.6.3-py3-none-any.whl (1.9 MB)
Collecting nltk>=3.5
  Using cached nltk-3.7-py3-none-any.whl (1.5 MB)
Requirement already satisfied: pillow>=8.1.2 in <PATH_TO_ENV>/lib/python3.8/site-packages (from openvino-dev) (9.0.0)
Requirement already satisfied: yamlloader>=0.5 in <PATH_TO_ENV>/lib/python3.8/site-packages (from openvino-dev) (1.1.0)
Requirement already satisfied: addict>=2.4.0 in <PATH_TO_ENV>/lib/python3.8/site-packages (from openvino-dev) (2.4.0)
Collecting nibabel>=3.2.1
  Using cached nibabel-3.2.2-py3-none-any.whl (3.3 MB)
Collecting hyperopt~=0.1.2
  Using cached hyperopt-0.1.2-py3-none-any.whl (115 kB)
Requirement already satisfied: texttable~=1.6.3 in <PATH_TO_ENV>/lib/python3.8/site-packages (from openvino-dev) (1.6.4)
Requirement already satisfied: progress>=1.5 in <PATH_TO_ENV>/lib/python3.8/site-packages (from openvino-dev) (1.6)
Collecting parasail>=1.2.4
  Using cached parasail-1.2.4-py2.py3-none-manylinux2010_x86_64.whl (14.1 MB)
Collecting openvino==2021.4.2
  Using cached openvino-2021.4.2-3976-cp38-cp38-manylinux2014_x86_64.whl (28.9 MB)
Collecting scikit-learn>=0.24.1
  Using cached scikit_learn-1.0.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.7 MB)
Requirement already satisfied: fast-ctc-decode>=0.2.5 in <PATH_TO_ENV>/lib/python3.8/site-packages (from openvino-dev) (0.3.0)
Requirement already satisfied: tokenizers>=0.10.1 in <PATH_TO_ENV>/lib/python3.8/site-packages (from openvino-dev) (0.11.5)
Requirement already satisfied: six in <PATH_TO_ENV>/lib/python3.8/site-packages (from hyperopt~=0.1.2->openvino-dev) (1.16.0)
Collecting future
  Using cached future-0.18.2-py3-none-any.whl
Requirement already satisfied: pymongo in <PATH_TO_ENV>/lib/python3.8/site-packages (from hyperopt~=0.1.2->openvino-dev) (4.0.1)
Requirement already satisfied: setuptools in <PATH_TO_ENV>/lib/python3.8/site-packages (from nibabel>=3.2.1->openvino-dev) (56.0.0)
Requirement already satisfied: packaging>=14.3 in <PATH_TO_ENV>/lib/python3.8/site-packages (from nibabel>=3.2.1->openvino-dev) (21.3)
Requirement already satisfied: regex>=2021.8.3 in <PATH_TO_ENV>/lib/python3.8/site-packages (from nltk>=3.5->openvino-dev) (2022.1.18)
Collecting click
  Using cached click-8.0.4-py3-none-any.whl (97 kB)
Requirement already satisfied: joblib in <PATH_TO_ENV>/lib/python3.8/site-packages (from nltk>=3.5->openvino-dev) (1.1.0)
Requirement already satisfied: python-dateutil>=2.7.3 in <PATH_TO_ENV>/lib/python3.8/site-packages (from pandas~=1.1.5->openvino-dev) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in <PATH_TO_ENV>/lib/python3.8/site-packages (from pandas~=1.1.5->openvino-dev) (2021.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in <PATH_TO_ENV>/lib/python3.8/site-packages (from requests>=2.25.1->openvino-dev) (1.26.8)
Requirement already satisfied: idna<4,>=2.5 in <PATH_TO_ENV>/lib/python3.8/site-packages (from requests>=2.25.1->openvino-dev) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in <PATH_TO_ENV>/lib/python3.8/site-packages (from requests>=2.25.1->openvino-dev) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in <PATH_TO_ENV>/lib/python3.8/site-packages (from requests>=2.25.1->openvino-dev) (2.0.12)
Collecting tifffile>=2019.7.26
  Using cached tifffile-2022.2.9-py3-none-any.whl (180 kB)
Collecting PyWavelets>=1.1.1
  Using cached PyWavelets-1.2.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (6.3 MB)
Collecting imageio>=2.4.1
  Using cached imageio-2.16.0-py3-none-any.whl (3.3 MB)
Requirement already satisfied: threadpoolctl>=2.0.0 in <PATH_TO_ENV>/lib/python3.8/site-packages (from scikit-learn>=0.24.1->openvino-dev) (3.1.0)
  Using cached imageio-2.15.0-py3-none-any.whl (3.3 MB)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in <PATH_TO_ENV>/lib/python3.8/site-packages (from packaging>=14.3->nibabel>=3.2.1->openvino-dev) (3.0.7)
Installing collected packages: numpy, networkx, future, editdistance, defusedxml, click, tifffile, scipy, rawpy, PyWavelets, parasail, pandas, openvino, opencv-python, nltk, nibabel, imageio, scikit-learn, scikit-image, hyperopt, openvino-dev
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.2
    Uninstalling numpy-1.22.2:
      Successfully uninstalled numpy-1.22.2
ERROR: Could not install packages due to an OSError: [Errno 39] Directory not empty: '<PATH_TO_ENV>/lib/python3.8/site-packages/~~mpy.libs'
Traceback (most recent call last):
  File "<PATH_TO_ENV>/lib/python3.8/site-packages/nebullvm/inference_learners/openvino.py", line 23, in <module>
    from openvino.inference_engine import IECore
ModuleNotFoundError: No module named 'openvino'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "test_pytorch.py", line 3, in <module>
    from nebullvm import optimize_torch_model
  File "<PATH_TO_ENV>/lib/python3.8/site-packages/nebullvm/__init__.py", line 1, in <module>
    from nebullvm.api.frontend.torch import optimize_torch_model  # noqa F401
  File "<PATH_TO_ENV>/lib/python3.8/site-packages/nebullvm/api/frontend/torch.py", line 10, in <module>
    from nebullvm.optimizers.multi_compiler import MultiCompilerOptimizer
  File "<PATH_TO_ENV>/lib/python3.8/site-packages/nebullvm/optimizers/__init__.py", line 5, in <module>
    from nebullvm.optimizers.openvino import OpenVinoOptimizer
  File "<PATH_TO_ENV>/lib/python3.8/site-packages/nebullvm/optimizers/openvino.py", line 5, in <module>
    from nebullvm.inference_learners.openvino import (
  File "<PATH_TO_ENV>/lib/python3.8/site-packages/nebullvm/inference_learners/openvino.py", line 33, in <module>
    from openvino.inference_engine import IECore
ModuleNotFoundError: No module named 'openvino'

The error about not having a module named openvino was present even when I ran`python -c "import nebullvm"` but since the README.md asks to ignore import errors, I did.
I tried `pip install openvino` but openvino needs numpy < 1.20 while tensorflow needs numpy >= 1.20 so there were incompatibilities.

My specifications:
python 3.8
torch 1.10.2+cu13
CPU: intel i5-9300H
PC: Acer Predator Helios PH315-52 V1.12
OS: Arch Linux x86_64

**Comment by morgoth95** [comment]
Hi IamMarcIvanov, thank you for reporting the issue! I'm working on it right now, will fix it for the next release!

**Comment by jagumiel** [comment]
Just in case it might be useful to someone... I'm getting a similar error with numpy:

```
ERROR: tf2onnx 1.9.3 has requirement flatbuffers~=1.12, but you'll have flatbuffers 2.0 which is incompatible.
ERROR: tensorflow 2.8.0 has requirement numpy>=1.20, but you'll have numpy 1.19.5 which is incompatible.
ERROR: imageio 2.16.1 has requirement numpy>=1.20.0, but you'll have numpy 1.19.5 which is incompatible.
```
**My specs:**
Python: 3.8.10
TensorFlow2: 2.8.0
PC: Virtual Machine (Linux-Lite 5.4 with 10GB RAM)
